services:
  app:
    build:
      context: .
      target: local 
      args:
        arg_model_version: 0.0.3 # set Model version to test
    container_name: latam-app
    environment:
      PORTT: 8000
      env: local
    volumes: 
      - ./Model/:/Model/
      - ./docs:/docs/
    ports:
      - '8000:8000'
    restart: "no"
  
