apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: latam-ml-service 
spec:
  template:
    metadata:
      name: latam-ml-service-prodv-1-0-1 # change the name of the instace to deploy a new version of the service 
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/aa-study/latam-repo/latam-ml-api:production
        env:
        - name: env 
          value: production

        # ports:
        # - name: h2c
        #   containerPort: 8000 
