
name: 'Latam ML micro-service'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: checks cicd
        run: |
          cd main 
          ls -a 
        shell: bash
      - name: checks version
        run: |
         echo "ML_version=$(echo `cat main/version.txt`)" >> $GITHUB_ENV
      - name: test version
        run: echo $ML_version

